
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>


namespace facebook::react {
class RNUITextViewChildEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  struct OnPress {
      int target;
    };

  struct OnLongPress {
      int target;
    };
  void onPress(OnPress value) const;

  void onLongPress(OnLongPress value) const;
};
class RNUITextViewEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  struct OnTextLayout {
      int target;
    std::vector<std::string> lines;
    };
  void onTextLayout(OnTextLayout value) const;
};
} // namespace facebook::react
